<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <div class="field mobile">
        <label for="mobile" class="label"><span><?php /* @escapeNotVerified */ echo __('Enter Mobile Number') ?></span></label>
        <div class="control">
            <input type="text" maxlength="10" minlength="10" name="mobile" id="mobile" title="<?php /* @escapeNotVerified */ echo __('Mobile Number') ?>" class="input-text required-entry validate-length maximum-length-10 minimum-length-10 validate-digits" data-validate="{required:true,'validate-number':true}" autocomplete="off">
        </div>
    </div>
</fieldset>

<!--<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <div class="field mobile">
        <label for="mobile" class="label"><span><?php /* @escapeNotVerified */ echo __('Enter Mobile Number') ?></span></label>
        <div class="control">
            <input type="text" name="mobile" id="mobile" title="<?php /* @escapeNotVerified */ echo __('Mobile Number') ?>" class="input-text" data-validate="{required:true}" autocomplete="off">
        </div>
    </div>
</fieldset>
-->