<?php

$pageurl = $this->getUrl();

?>
<style>
    
    .container.successmsg {
    margin-top: -800px;
    background: #000;
    width: 55%;
    padding: 10px;
    color: #fff;
    font-weight: bold;
}
</style>

<div class="container successmsg">
    
   <div class="text-center"> Your registration process is completed successfully. You will be redirected to homepagewithin 5 secs. </div>
    
</div>

<script type="text/javascript">

setTimeout(function(){ location.href = '<?php echo $pageurl;  ?>'},5000);
</script>



